<?php
/* if change this please enter the parent in the top of permissions_settings array and the children under it for given the right style */
$GLOBALS['permissions_settings'] = array(
    /*parent*/
    'users',
    /*start Sup*/
    'users_add',
    'users_view',
    'users_edit',
    'users_delete',
    'users_active',
    /*End Sup*/

    'instructors',
    'instructors_add',
    'instructors_edit',
    'instructors_delete',
    'instructors_publish',
    'instructors_view',

    'mobile_notifications',
    'mobile_notifications_add',

    'blocked_users',
    'blocked_users_view',

    'profiles',
    'profiles_add',
    'profiles_edit',
    'profiles_delete',
    'profiles_active',
    'profiles_view',

    'mlm_requests',
    'mlm_requests_view',
    'mlm_requests_send',

    'courses_resources',
    'courses_resources_add',
    'courses_resources_edit',
    'courses_resources_delete',
    'courses_resources_active',
    'courses_resources_publish',
    'courses_resources_view',

    'webinar_resources',
    'webinar_resources_add',
    'webinar_resources_edit',
    'webinar_resources_delete',
    'webinar_resources_active',
    'webinar_resources_view',

    'webinars',
    'webinars_add',
    'webinars_edit',
    'webinars_delete',
    'webinars_active',
    'webinars_view',
    'webinars_convert',

    'live',
    'live_add',
    'live_edit',
    'live_delete',
    'live_active',
    'live_view',


    'old_urls',
    'old_urls_add',
    'old_urls_edit',
    'old_urls_delete',
    'old_urls_view',

    'books',
    'books_add',
    'books_edit',
    'books_delete',
    'books_publish',
    'books_view',

    'tags',
    'tags_add',
    'tags_edit',
    'tags_delete',
    'tags_view',

    'demo_medical_logs',
    'demo_medical_logs_add',
    'demo_medical_logs_edit',
    'demo_medical_logs_delete',
    'demo_medical_logs_view',

    'diplomas',
    'diplomas_add',
    'diplomas_edit',
    'diplomas_delete',
    'diplomas_active',
    'diplomas_view',

    'international_diplomas',
    'international_diplomas_add',
    'international_diplomas_edit',
    'international_diplomas_delete',
    'international_diplomas_active',
    'international_diplomas_view',

    'international_categories',
    'international_categories_add',
    'international_categories_edit',
    'international_categories_delete',
    'international_categories_publish',
    'international_categories_view',

    'courses',
    'courses_add',
    'courses_edit',
    'courses_delete',
    'courses_publish',
    'courses_view',
    'courses_preview',

    'courses_questions',
    'courses_questions_add',
    'courses_questions_edit',
    'courses_questions_delete',
    'courses_questions_active',
    'courses_questions_view',

    'modules_questions',
    'modules_questions_add',
    'modules_questions_edit',
    'modules_questions_delete',
    'modules_questions_active',
    'modules_questions_view',

    'modules_courses',
    'modules_courses_add',
    'modules_courses_edit',
    'modules_courses_delete',
    'modules_courses_active',
    'modules_courses_view',

    /*parent*/
    'our_products',
    /*start Sup*/
    'our_products_add',
    'our_products_view',
    'our_products_edit',
    'our_products_delete',
    'our_products_publish',
    'our_products_url',
    /*End Sup*/
    /*parent*/
    'our_products_courses',
    /*start Sup*/
    'our_products_courses_add',
    'our_products_courses_view',
    'our_products_courses_edit',
    'our_products_courses_delete',
    'our_products_courses_active',
    'our_products_courses_url',
    /*End Sup*/

    'static_pages',
    'static_pages_add',
    'static_pages_edit',
    'static_pages_delete',
    'static_pages_view',
    'static_pages_publish',

    'apple_users',
    'apple_users_add',
    'apple_users_edit',
    'apple_users_delete',
    'apple_users_view',

    'apple_products',
    'apple_products_add',
    'apple_products_edit',
    'apple_products_delete',
    'apple_products_view',

    'installment_payment',
    'installment_payment_add',
    'installment_payment_edit',
    'installment_payment_delete',
    'installment_payment_view',
    'installment_payment_publish',

    'events',
    'events_add',
    'events_edit',
    'events_delete',
    'events_view',
    'events_publish',

    'users_sessions',
    'users_sessions_view',

    'normal_user',
    'normal_user_add',
    'normal_user_edit',
    'normal_user_delete',
    'normal_user_view',
    'normal_user_publish',
    'normal_user_reset_password',
    'normal_user_show_password',
    'normal_user_edit_sponserid',

    'recruit_users',
    'recruit_users_add',
    'recruit_users_edit',
    'recruit_users_delete',
    'recruit_users_view',
    'recruit_users_publish',

    'partner_requests',
    'partner_requests_add',
    'partner_requests_edit',
    'partner_requests_delete',
    'partner_requests_view',
    'partner_requests_publish',

    'become_instructor',
    'become_instructor_add',
    'become_instructor_edit',
    'become_instructor_delete',
    'become_instructor_view',
    'become_instructor_publish',


    'testimonials',
    'testimonials_add',
    'testimonials_edit',
    'testimonials_delete',
    'testimonials_view',
    'testimonials_publish',

    'gallery',
    'gallery_add',
    'gallery_edit',
    'gallery_delete',
    'gallery_view',
    'gallery_publish',

    'employee',
    'employee_add',
    'employee_edit',
    'employee_delete',
    'employee_view',
    'employee_publish',

    'diploma_courses',
    'diploma_courses_add',
    'diploma_courses_edit',
    'diploma_courses_delete',
    'diploma_courses_view',
    'diploma_courses_publish',

    'international_diploma_courses',
    'international_diploma_courses_add',
    'international_diploma_courses_edit',
    'international_diploma_courses_delete',
    'international_diploma_courses_view',
    'international_diploma_courses_publish',

    'diploma_user_courses',
    'diploma_user_courses_add',
    'diploma_user_courses_edit',
    'diploma_user_courses_delete',
    'diploma_user_courses_delete_all',
    'diploma_user_courses_view',
    //'diploma_user_courses_publish',
    'diploma_user_courses_copy',

    'international_diploma_user_courses',
    'international_diploma_user_courses_add',
    'international_diploma_user_courses_edit',
    'international_diploma_user_courses_delete',
    'international_diploma_user_courses_view',
    //'international_diploma_user_courses_publish',
    'international_diploma_user_courses_copy',

    'faq',
    'faq_add',
    'faq_edit',
    'faq_delete',
    'faq_view',
    'faq_publish',

    'site_faq',
    'site_faq_add',
    'site_faq_edit',
    'site_faq_delete',
    'site_faq_view',
    'site_faq_publish',

    'site_faq_type',
    'site_faq_type_add',
    'site_faq_type_edit',
    'site_faq_type_delete',
    'site_faq_type_view',
    'site_faq_type_publish',

    'courses_offers',
    'courses_offers_add',
    'courses_offers_edit',
    'courses_offers_delete',
    'courses_offers_view',
    'courses_offers_publish',

    'companies_admins',
    'companies_admins_add',
    'companies_admins_edit',
    'companies_admins_delete',
    'companies_admins_view',

    'automation',
    'automation_add',
    'automation_edit',
    'automation_delete',
    'automation_view',
    'automation_publish',

    'courses_sections',
    'courses_sections_add',
    'courses_sections_edit',
    'courses_sections_delete',
    'courses_sections_view',
    'courses_sections_publish',

    'tpay_price_book',
    'tpay_price_book_add',
    'tpay_price_book_edit',
    'tpay_price_book_delete',
    'tpay_price_book_view',
    'tpay_price_book_publish',

    'recruitment_employees',
    'recruitment_employees_add',
    'recruitment_employees_edit',
    'recruitment_employees_delete',
    'recruitment_employees_view',
    'recruitment_employees_publish',

    'recruitment_jobs',
    'recruitment_jobs_add',
    'recruitment_jobs_edit',
    'recruitment_jobs_delete',
    'recruitment_jobs_view',
    'recruitment_jobs_publish',

    'recruitment_industries',
    'recruitment_industries_add',
    'recruitment_industries_edit',
    'recruitment_industries_delete',
    'recruitment_industries_view',
    'recruitment_industries_publish',

    'recruitment_job_types',
    'recruitment_job_types_add',
    'recruitment_job_types_edit',
    'recruitment_job_types_delete',
    'recruitment_job_types_view',
    'recruitment_job_types_publish',

    'recruitment_currencies',
    'recruitment_currencies_add',
    'recruitment_currencies_edit',
    'recruitment_currencies_delete',
    'recruitment_currencies_view',
    'recruitment_currencies_publish',

    'recruitment_jobs_types',
    'recruitment_jobs_types_add',
    'recruitment_jobs_types_edit',
    'recruitment_jobs_types_delete',
    'recruitment_jobs_types_view',
    'recruitment_jobs_types_publish',

    'recruitment_job_roles',
    'recruitment_job_roles_add',
    'recruitment_job_roles_edit',
    'recruitment_job_roles_delete',
    'recruitment_job_roles_view',
    'recruitment_job_roles_publish',

    'recruitment_jobs_roles',
    'recruitment_jobs_roles_add',
    'recruitment_jobs_roles_edit',
    'recruitment_jobs_roles_delete',
    'recruitment_jobs_roles_view',
    'recruitment_jobs_roles_publish',

    'recruitment_employee_job_apply',
    'recruitment_employee_job_apply_add',
    'recruitment_employee_job_apply_edit',
    'recruitment_employee_job_apply_delete',
    'recruitment_employee_job_apply_view',
    'recruitment_employee_job_apply_publish',

    'modules_users_summary',
    'modules_users_summary_edit',
    'modules_users_summary_view',

    'course_curriculum',
    'course_curriculum_add',
    'course_curriculum_edit',
    'course_curriculum_delete',
    'course_curriculum_view',
    'course_curriculum_publish',
    'course_curriculum_preview_audio',
    'course_curriculum_preview_video',

    'all_categories',
    'all_categories_add',
    'all_categories_edit',
    'all_categories_delete',
    'all_categories_view',
    'all_categories_publish',

    'diplomas_targets',
    'diplomas_targets_add',
    'diplomas_targets_edit',
    'diplomas_targets_delete',
    'diplomas_targets_view',
    'diplomas_targets_publish',

    'mba_charge_transaction',
    'mba_charge_transaction_add',
    'mba_charge_transaction_edit',
    'mba_charge_transaction_delete',
    'mba_charge_transaction_view',
    'mba_charge_transaction_publish',
    'mba_charge_transaction_copy',

    'session_courses_views',
    'session_courses_views_add',
    'session_courses_views_edit',
    'session_courses_views_delete',
    'session_courses_views_view',
    'session_courses_views_publish',

    'session_successtories_views',
    'session_successtories_views_add',
    'session_successtories_views_edit',
    'session_successtories_views_delete',
    'session_successtories_views_view',
    'session_successtories_views_publish',

    'session_webinars_views',
    'session_webinars_views_add',
    'session_webinars_views_edit',
    'session_webinars_views_delete',
    'session_webinars_views_view',
    'session_webinars_views_publish',

    'session_diplomas_views',
    'session_diplomas_views_view',

    'courses_views',
    'courses_views_add',
    'courses_views_edit',
    'courses_views_delete',
    'courses_views_view',
    'courses_views_publish',

    'international_diplomas_views',
    'international_diplomas_views_add',
    'international_diplomas_views_edit',
    'international_diplomas_views_delete',
    'international_diplomas_views_view',
    'international_diplomas_views_publish',

    'diplomas_charge_transaction_suspend_log',
    'diplomas_charge_transaction_suspend_log_add',
    'diplomas_charge_transaction_suspend_log_edit',
    'diplomas_charge_transaction_suspend_log_delete',
    'diplomas_charge_transaction_suspend_log_view',
    'diplomas_charge_transaction_suspend_log_publish',

    'international_diplomas_charge_transaction_suspend_log',
    'international_diplomas_charge_transaction_suspend_log_add',
    'international_diplomas_charge_transaction_suspend_log_edit',
    'international_diplomas_charge_transaction_suspend_log_delete',
    'international_diplomas_charge_transaction_suspend_log_view',
    'international_diplomas_charge_transaction_suspend_log_publish',

    'medical_charge_transaction_suspend_log',
    'medical_charge_transaction_suspend_log_add',
    'medical_charge_transaction_suspend_log_edit',
    'medical_charge_transaction_suspend_log_delete',
    'medical_charge_transaction_suspend_log_view',
    'medical_charge_transaction_suspend_log_publish',

    'diplomas_charge_transaction',
    'diplomas_charge_transaction_add',
    'diplomas_charge_transaction_edit',
    'diplomas_charge_transaction_delete',
    'diplomas_charge_transaction_view',
    'diplomas_charge_transaction_publish',
    'diplomas_charge_transaction_copy',
    'diplomas_charge_transaction_add_courses',

    'international_diplomas_charge_transaction',
    'international_diplomas_charge_transaction_add',
    'international_diplomas_charge_transaction_edit',
    'international_diplomas_charge_transaction_delete',
    'international_diplomas_charge_transaction_view',
    'international_diplomas_charge_transaction_publish',
    'international_diplomas_charge_transaction_copy',
//    'international_diplomas_charge_transaction_add_courses',

    'diplomas_companies_charge_transaction',
    'diplomas_companies_charge_transaction_add',
    'diplomas_companies_charge_transaction_edit',
    'diplomas_companies_charge_transaction_delete',
    'diplomas_companies_charge_transaction_view',
//    'diplomas_companies_charge_transaction_publish',
    'diplomas_companies_charge_transaction_copy',
    'diplomas_companies_charge_transaction_add_courses',

    'courses_curriculum_certificates',
    'courses_curriculum_certificates_add',
    'courses_curriculum_certificates_edit',
    'courses_curriculum_certificates_delete',
    'courses_curriculum_certificates_view',
    'courses_curriculum_certificates_publish',
    'courses_curriculum_certificates_copy',

    'mba_certificates',
    'mba_certificates_add',
    'mba_certificates_edit',
    'mba_certificates_delete',
    'mba_certificates_view',

    'charge_transaction',
    'charge_transaction_add',
    'charge_transaction_edit',
    'charge_transaction_delete',
    'charge_transaction_view',
    'charge_transaction_publish',
    'charge_transaction_copy',

    'apple_users_charge_transactions',
    'apple_users_charge_transactions_add',
    'apple_users_charge_transactions_edit',
    'apple_users_charge_transactions_delete',
    'apple_users_charge_transactions_view',

    'payment_transaction',
    'payment_transaction_add',
    'payment_transaction_edit',
    'payment_transaction_delete',
    'payment_transaction_view',
    'payment_transaction_publish',

    'support_transaction',
    'support_transaction_add',
    'support_transaction_edit',
    'support_transaction_delete',
    'support_transaction_view',
    'support_transaction_publish',

    'webinars_views',
    'webinars_views_add',
    'webinars_views_edit',
    'webinars_views_delete',
    'webinars_views_view',
    'webinars_views_publish',

    'successtories_views',
    'successtories_views_add',
    'successtories_views_edit',
    'successtories_views_delete',
    'successtories_views_view',
    'successtories_views_publish',

    'contactus',
    'contactus_view',

    'sub_categories',
    'sub_categories_add',
    'sub_categories_edit',
    'sub_categories_delete',
    'sub_categories_view',
    'sub_categories_publish',

    'successtories_categories',
    'successtories_categories_add',
    'successtories_categories_edit',
    'successtories_categories_delete',
    'successtories_categories_view',
    'successtories_categories_publish',

    'books_categories',
    'books_categories_add',
    'books_categories_edit',
    'books_categories_delete',
    'books_categories_view',
    'books_categories_publish',

    'books_playlist',
    'books_playlist_add',
    'books_playlist_edit',
    'books_playlist_delete',
    'books_playlist_view',
    'books_playlist_publish',

    'webinars_categories',
    'webinars_categories_add',
    'webinars_categories_edit',
    'webinars_categories_delete',
    'webinars_categories_view',
    'webinars_categories_publish',

    'company',
    'company_add',
    'company_edit',
    'company_delete',
    'company_view',
    'company_publish',

    'abuse',
    'abuse_view',

    'recruit',
    'recruit_add',
    'recruit_edit',
    'recruit_delete',
    'recruit_view',
    'recruit_publish',

    'recruitment_companies',
    'recruitment_companies_add',
    'recruitment_companies_edit',
    'recruitment_companies_delete',
    'recruitment_companies_view',
    'recruitment_companies_publish',

    'diploma_certificates',
    'diploma_certificates_delete',
    'diploma_certificates_view',
    'diploma_certificates_publish',
    'diploma_certificates_copy',
    'diploma_certificates_view_exams_result',

    'international_diploma_certificates',
    'international_diploma_certificates_delete',
    'international_diploma_certificates_view',
    'international_diploma_certificates_publish',
    'international_diploma_certificates_copy',

    /*parent*/
    'modules_trainings',
    /*start Sup*/
    'modules_trainings_add',
    'modules_trainings_view',
    'modules_trainings_edit',
    'modules_trainings_delete',
    'modules_trainings_active',
    /*End Sup*/

    /*parent*/
    'modules_trainings_questions',
    /*start Sup*/
    'modules_trainings_questions_view',
    'modules_trainings_questions_edit',
    'modules_trainings_questions_delete',
    'modules_trainings_questions_active',
    /*End Sup*/

    /*parent*/
    'modules',
    /*start Sup*/
    'modules_add',
    'modules_edit',
    'modules_delete',
    'modules_active',
    'modules_view',
    /*End Sup*/

    /*parent*/
    'modules_projects',
    /*start Sup*/
    'modules_projects_add',
    'modules_projects_edit',
    'modules_projects_delete',
    'modules_projects_active',
    'modules_projects_view',
    /*End Sup*/

    /*parent*/
    'modules_users_projects',
    /*start Sup*/
    'modules_users_projects_add',
    'modules_users_projects_edit',
    'modules_users_projects_delete',
    'modules_users_projects_active',
    'modules_users_projects_view',
    /*End Sup*/

    /*parent*/
    'modules_helper_courses',
    /*start Sup*/
    'modules_helper_courses_add',
    'modules_helper_courses_edit',
    'modules_helper_courses_delete',
    'modules_helper_courses_active',
    'modules_helper_courses_view',
    /*End Sup*/

    /*parent*/
    'successstories',
    /*start Sup*/
    'successstories_add',
    'successstories_edit',
    'successstories_delete',
    'successstories_publish',
    'successstories_view',
    /*End Sup*/

    /*parent*/
    'articles',
    /*start Sup*/
    'articles_add',
    'articles_edit',
    'articles_delete',
    'articles_publish',
    'articles_view',
    /*End Sup*/

    /*parent*/
    'categories',
    /*start Sup*/
    'categories_add',
    'categories_edit',
    'categories_delete',
    'categories_active',
    'categories_view',
    /*End Sup*/

    /*parent*/
    'author',
    /*start Sup*/
    'author_add',
    'author_edit',
    'author_delete',
    'author_view',
    'author_publish',
    /*End Sup*/

    /*parent*/
    'settings',
    /*start Sup*/
    'system',
    'app_settings_edit',
    'seo_sitemap_edit',
    'subscription_prices_edit',
    'request_courses',
    'request_courses_view',
    /*End Sup*/

    'books_requests',
    'books_requests_view',

    'company_request',
    'company_request_view',
    'company_request_add',
    'company_request_edit',
    'company_request_delete',


    /*parent*/
    'our_partner',
    /*start Sup*/
    'our_partner_add',
    'our_partner_view',
    'our_partner_edit',
    'our_partner_delete',
    'our_partner_publish',
    /*End Sup*/

    /*parent*/
    'our_partner_flags',
    /*start Sup*/
    'our_partner_flags_add',
    'our_partner_flags_view',
    'our_partner_flags_edit',
    'our_partner_flags_delete',
    'our_partner_flags_publish',
    /*End Sup*/

    'courses_categories',
    'courses_categories_add',
    'courses_categories_edit',
    'courses_categories_delete',
    'courses_categories_view',
    'courses_categories_publish',

    'user_contractid',
    'user_contractid_add',
    'user_contractid_edit',
    'user_contractid_delete',
    'user_contractid_view',
    'user_contractid_publish',

    'user_contractid_notifications',
    'user_contractid_notifications_add',
    'user_contractid_notifications_edit',
    'user_contractid_notifications_delete',
    'user_contractid_notifications_view',
    'user_contractid_notifications_publish',

    'users_curriculum_answers',
    'users_curriculum_answers_add',
    'users_curriculum_answers_edit',
    'users_curriculum_answers_delete',
    'users_curriculum_answers_view',
    'users_curriculum_answers_publish',

    'my_courses',
    'my_courses_add',
    'my_courses_edit',
    'my_courses_delete',
    'my_courses_view',
    'my_courses_publish',
    'my_courses_copy',

    'survey',
    'survey_view',

    'survey_clients',
    'survey_clients_view',


    'feedback',
    'feedback_view',
    'feedback_edit',

    'rating',
    'rating_view',

    'medical_charge_transactions',
    'medical_charge_transactions_add',
    'medical_charge_transactions_edit',
    'medical_charge_transactions_delete',
    'medical_charge_transactions_active',
    'medical_charge_transactions_view',
    'medical_charge_transactions_copy',

    'medical_categories_charge_transactions',
    'medical_categories_charge_transactions_add',
    'medical_categories_charge_transactions_edit',
    'medical_categories_charge_transactions_delete',
    'medical_categories_charge_transactions_active',
    'medical_categories_charge_transactions_view',
    'medical_categories_charge_transactions_copy',

    'medical_categories',
    'medical_categories_add',
    'medical_categories_edit',
    'medical_categories_delete',
    'medical_categories_view',
    'medical_categories_publish',

    'initiative_sections',
    'initiative_sections_add',
    'initiative_sections_edit',
    'initiative_sections_delete',
    'initiative_sections_view',
    'initiative_sections_publish',

    'initiative_videos',
    'initiative_videos_add',
    'initiative_videos_edit',
    'initiative_videos_delete',
    'initiative_videos_view',
    'initiative_videos_publish',

    'initiative_articles',
    'initiative_articles_add',
    'initiative_articles_edit',
    'initiative_articles_delete',
    'initiative_articles_view',
    'initiative_articles_publish',

    'users_cvs',
    'users_cvs_view',
    'users_cvs_download',

    'lite_version_charge_transaction',
    'lite_version_charge_transaction_add',
    'lite_version_charge_transaction_edit',
    'lite_version_charge_transaction_delete',
    'lite_version_charge_transaction_active',
    'lite_version_charge_transaction_view',


    'diplomas_courses_user_plan',
    'diplomas_courses_user_plan_add',
    'diplomas_courses_user_plan_edit',
    'diplomas_courses_user_plan_delete',
    'diplomas_courses_user_plan_delete_all',
    'diplomas_courses_user_plan_active',
    'diplomas_courses_user_plan_view',
    'diplomas_courses_user_plan_delete_selected',

    'international_diplomas_courses_user_plan',
    'international_diplomas_courses_user_plan_add',
    'international_diplomas_courses_user_plan_edit',
    'international_diplomas_courses_user_plan_delete',
    'international_diplomas_courses_user_plan_active',
    'international_diplomas_courses_user_plan_view',

    'mba_courses_user_plan',
    'mba_courses_user_plan_add',
    'mba_courses_user_plan_edit',
    'mba_courses_user_plan_delete',
    'mba_courses_user_plan_active',
    'mba_courses_user_plan_view',

    'users_suspend_liteversion',
    'users_suspend_liteversion_add',
    'users_suspend_liteversion_edit',
    'users_suspend_liteversion_delete',
    'users_suspend_liteversion_view',

    'users_suspend',
    'users_suspend_view',

    'promotion_code_used',
    'promotion_code_used_view',
    'promotion_code_used_report1',
    'promotion_code_used_report2',

    'promotion_code',
    'promotion_code_add',


    'courses_QandA',
    'courses_QandA_edit',
    'courses_QandA_view',

    'quality',
    'mba_progress',

    'companies_charge_transaction',
    'companies_charge_transaction_delete',
    'companies_charge_transaction_view',

    'lite_version_companies_charge_transaction',
    'lite_version_companies_charge_transaction_delete',
    'lite_version_companies_charge_transaction_view',

    'mba_companies_charge_transaction',
    'mba_companies_charge_transaction_delete',
    'mba_companies_charge_transaction_view',


    /*'survey2',
    'survey2_view',

    'survey2_clients',
    'survey2_clients_view',*/


    'profile',
    'dashboard',
    'remove_medical',
    'view_all_rows',
);
$GLOBALS['sup_permissions'] = array(
    'users' => array('users_add', 'users_view', 'users_edit', 'users_delete', 'users_active'),
    'users_suspend' => array('users_suspend_view'),
    'promotion_code_used' => array('promotion_code_used_view','promotion_code_used_report1','promotion_code_used_report2'),
    'quality' => array('mba_progress'),
    'promotion_code' => array('promotion_code_add'),
    'mobile_notifications' => array('mobile_notifications_add'),
    'users_suspend_liteversion' => array('users_suspend_liteversion_add', 'users_suspend_liteversion_view', 'users_suspend_liteversion_edit', 'users_suspend_liteversion_delete'),
    'instructors' => array('instructors_add', 'instructors_view', 'instructors_edit', 'instructors_delete', 'instructors_publish'),
    'profiles' => array('profiles_add', 'profiles_edit', 'profiles_delete', 'profiles_active', 'profiles_view'),
    'courses_resources' => array('courses_resources_add', 'courses_resources_edit', 'courses_resources_delete', 'courses_resources_active', 'courses_resources_view', 'courses_resources_publish'),
    'webinar_resources' => array('webinar_resources_add', 'webinar_resources_edit', 'webinar_resources_delete', 'webinar_resources_active', 'webinar_resources_view'),
    'webinars' => array('webinars_add', 'webinars_edit', 'webinars_delete', 'webinars_active', 'webinars_view', 'webinars_convert'),
    'live' => array('live_add', 'live_edit', 'live_delete', 'live_active', 'live_view'),
    'static_pages' => array('static_pages_add', 'static_pages_view', 'static_pages_edit', 'static_pages_delete', 'static_pages_publish'),
    'events' => array('events_add', 'events_view', 'events_edit', 'events_delete', 'events_publish'),
    'automation' => array('automation_add', 'automation_view', 'automation_edit', 'automation_delete', 'automation_publish'),
    'partner_requests' => array('partner_requests_add', 'partner_requests_view', 'partner_requests_edit', 'partner_requests_delete', 'partner_requests_publish'),
    'become_instructor' => array('become_instructor_add', 'become_instructor_view', 'become_instructor_edit', 'become_instructor_delete', 'become_instructor_publish'),
    'testimonials' => array('testimonials_add', 'testimonials_view', 'testimonials_edit', 'testimonials_delete', 'testimonials_publish'),
    'gallery' => array('gallery_add', 'gallery_view', 'gallery_edit', 'gallery_delete', 'gallery_publish'),
    'installment_payment' => array('installment_payment_add', 'installment_payment_view', 'installment_payment_edit', 'installment_payment_delete', 'installment_payment_publish'),
    'employee' => array('employee_add', 'employee_view', 'employee_edit', 'employee_delete', 'employee_publish'),
    'course_curriculum' => array('course_curriculum_add', 'course_curriculum_view', 'course_curriculum_edit', 'course_curriculum_delete', 'course_curriculum_publish','course_curriculum_preview_audio','course_curriculum_preview_video',),
    'company' => array('company_add', 'company_view', 'company_edit', 'company_delete', 'company_publish'),
    'users_curriculum_answers' => array('users_curriculum_answers_add', 'users_curriculum_answers_view', 'users_curriculum_answers_edit', 'users_curriculum_answers_delete', 'users_curriculum_answers_publish'),
    'recruitment_employees' => array('recruitment_employees_add', 'recruitment_employees_view', 'recruitment_employees_edit', 'recruitment_employees_delete', 'recruitment_employees_publish'),
    'recruit' => array('recruit_add', 'recruit_view', 'recruit_edit', 'recruit_delete', 'recruit_publish'),
    'recruitment_companies' => array('recruitment_companies_add', 'recruitment_companies_view', 'recruitment_companies_edit', 'recruitment_companies_delete', 'recruitment_companies_publish'),
    'recruitment_jobs' => array('recruitment_jobs_add', 'recruitment_jobs_view', 'recruitment_jobs_edit', 'recruitment_jobs_delete', 'recruitment_jobs_publish'),
    'recruitment_employee_job_apply' => array('recruitment_employee_job_apply_add', 'recruitment_employee_job_apply_view', 'recruitment_employee_job_apply_edit', 'recruitment_employee_job_apply_delete', 'recruitment_employee_job_apply_publish'),
    'recruitment_industries' => array('recruitment_industries_add', 'recruitment_industries_view', 'recruitment_industries_edit', 'recruitment_industries_delete', 'recruitment_industries_publish'),
    'recruitment_job_types' => array('recruitment_job_types_add', 'recruitment_job_types_view', 'recruitment_job_types_edit', 'recruitment_job_types_delete', 'recruitment_job_types_publish'),
    'recruitment_currencies' => array('recruitment_currencies_add', 'recruitment_currencies_view', 'recruitment_currencies_edit', 'recruitment_currencies_delete', 'recruitment_currencies_publish'),
    'recruitment_jobs_types' => array('recruitment_jobs_types_add', 'recruitment_jobs_types_view', 'recruitment_jobs_types_edit', 'recruitment_jobs_types_delete', 'recruitment_jobs_types_publish'),
    'recruitment_job_roles' => array('recruitment_job_roles_add', 'recruitment_job_roles_view', 'recruitment_job_roles_edit', 'recruitment_job_roles_delete', 'recruitment_job_roles_publish'),
    'recruitment_jobs_roles' => array('recruitment_jobs_roles_add', 'recruitment_jobs_roles_view', 'recruitment_jobs_roles_edit', 'recruitment_jobs_roles_delete', 'recruitment_jobs_roles_publish'),
    'diploma_courses' => array('diploma_courses_add', 'diploma_courses_view', 'diploma_courses_edit', 'diploma_courses_delete', 'diploma_courses_publish'),
    'international_diploma_courses' => array('international_diploma_courses_add', 'international_diploma_courses_view', 'international_diploma_courses_edit', 'international_diploma_courses_delete', 'international_diploma_courses_publish'),
    'diploma_user_courses' => array('diploma_user_courses_add', 'diploma_user_courses_view', 'diploma_user_courses_edit', 'diploma_user_courses_delete', 'diploma_user_courses_delete_all',/* 'diploma_user_courses_publish', */'diploma_user_courses_copy'),
    'international_diploma_user_courses' => array('international_diploma_user_courses_add', 'international_diploma_user_courses_view', 'international_diploma_user_courses_edit', 'international_diploma_user_courses_delete',/* 'international_diploma_user_courses_publish', */'international_diploma_user_courses_copy'),
    'diploma_certificates' => array('diploma_certificates_view', 'diploma_certificates_delete', 'diploma_certificates_publish', 'diploma_certificates_copy','diploma_certificates_view_exams_result'),
    'international_diploma_certificates' => array('international_diploma_certificates_view', 'international_diploma_certificates_delete', 'international_diploma_certificates_publish', 'international_diploma_certificates_copy'),
    'mba_certificates' => array('mba_certificates_add', 'mba_certificates_edit','mba_certificates_view', 'mba_certificates_delete'),
    'books' => array('books_add', 'books_edit', 'books_delete', 'books_publish', 'books_view'),
    'apple_users' => array('apple_users_add', 'apple_users_edit', 'apple_users_delete', 'apple_users_view'),
    'apple_products' => array('apple_products_add', 'apple_products_edit', 'apple_products_delete', 'apple_products_view'),
    'diplomas_targets' => array('diplomas_targets_add', 'diplomas_targets_edit', 'diplomas_targets_delete', 'diplomas_targets_publish', 'diplomas_targets_view'),
    'courses_offers' => array('courses_offers_add', 'courses_offers_edit', 'courses_offers_delete', 'courses_offers_publish', 'courses_offers_view'),
    'courses_sections' => array('courses_sections_add', 'courses_sections_edit', 'courses_sections_delete', 'courses_sections_publish', 'courses_sections_view'),
    'faq' => array('faq_add', 'faq_edit', 'faq_delete', 'faq_publish', 'faq_view'),
    'site_faq' => array('site_faq_add', 'site_faq_edit', 'site_faq_delete', 'site_faq_publish', 'site_faq_view'),
    'site_faq_type' => array('site_faq_type_add', 'site_faq_type_edit', 'site_faq_type_delete', 'site_faq_type_publish', 'site_faq_type_view'),
    'companies_admins' => array('companies_admins_add', 'companies_admins_edit', 'companies_admins_delete', 'companies_admins_view'),
    'courses_curriculum_certificates' => array('courses_curriculum_certificates_add', 'courses_curriculum_certificates_edit', 'courses_curriculum_certificates_delete', 'courses_curriculum_certificates_publish', 'courses_curriculum_certificates_view', 'courses_curriculum_certificates_copy'),
    'user_contractid' => array('user_contractid_add', 'user_contractid_edit', 'user_contractid_delete', 'user_contractid_publish', 'user_contractid_view'),
    'user_contractid_notifications' => array('user_contractid_notifications_add', 'user_contractid_notifications_edit', 'user_contractid_notifications_delete', 'user_contractid_notifications_publish', 'user_contractid_notifications_view'),
    'my_courses' => array('my_courses_add', 'my_courses_edit', 'my_courses_delete', 'my_courses_publish', 'my_courses_view', 'my_courses_copy'),
    'normal_user' => array('normal_user_add', 'normal_user_edit', 'normal_user_delete', 'normal_user_publish', 'normal_user_view', 'normal_user_reset_password', 'normal_user_show_password', 'normal_user_edit_sponserid'),
    'recruit_users' => array('recruit_users_add', 'recruit_users_edit', 'recruit_users_delete', 'recruit_users_publish', 'recruit_users_view'),
    'all_categories' => array('all_categories_add', 'all_categories_edit', 'all_categories_delete', 'all_categories_publish', 'all_categories_view'),
    'sub_categories' => array('sub_categories_add', 'sub_categories_edit', 'sub_categories_delete', 'sub_categories_publish', 'sub_categories_view'),
    'courses_categories' => array('courses_categories_add', 'courses_categories_edit', 'courses_categories_delete', 'courses_categories_publish', 'courses_categories_view'),
    'successtories_categories' => array('successtories_categories_add', 'successtories_categories_edit', 'successtories_categories_delete', 'successtories_categories_publish', 'successtories_categories_view'),
    'books_categories' => array('books_categories_add', 'books_categories_edit', 'books_categories_delete', 'books_categories_publish', 'books_categories_view'),
    'books_playlist' => array('books_playlist_add', 'books_playlist_edit', 'books_playlist_delete', 'books_playlist_publish', 'books_playlist_view'),
    'webinars_categories' => array('webinars_categories_add', 'webinars_categories_edit', 'webinars_categories_delete', 'webinars_categories_publish', 'webinars_categories_view'),
    'medical_categories' => array('medical_categories_add', 'medical_categories_edit', 'medical_categories_delete', 'medical_categories_publish', 'medical_categories_view'),
    'courses' => array('courses_add', 'courses_edit', 'courses_delete', 'courses_publish', 'courses_view','courses_preview'),
    'tpay_price_book' => array('tpay_price_book_add', 'tpay_price_book_edit', 'tpay_price_book_delete', 'tpay_price_book_publish', 'tpay_price_book_view'),
    'courses_questions' => array('courses_questions_add', 'courses_questions_edit', 'courses_questions_delete', 'courses_questions_active', 'courses_questions_view'),
    'diplomas' => array('diplomas_add', 'diplomas_edit', 'diplomas_delete', 'diplomas_active', 'diplomas_view'),
    'international_diplomas' => array('international_diplomas_add', 'international_diplomas_edit', 'international_diplomas_delete', 'international_diplomas_active', 'international_diplomas_view'),
    'international_categories' => array('international_categories_add', 'international_categories_edit', 'international_categories_delete', 'international_categories_publish', 'international_categories_view'),
    'tags' => array('tags_add', 'tags_edit', 'tags_delete', 'tags_view'),
    'users_sessions' => array('users_sessions_view'),
    'old_urls' => array('old_urls_add', 'old_urls_edit', 'old_urls_delete', 'old_urls_view'),
    'modules_questions' => array('modules_questions_add', 'modules_questions_edit', 'modules_questions_delete', 'modules_questions_active', 'modules_questions_view'),
    'modules_courses' => array('modules_courses_add', 'modules_courses_edit', 'modules_courses_delete', 'modules_courses_active', 'modules_courses_view'),
    'our_products' => array('our_products_add', 'our_products_view', 'our_products_edit', 'our_products_delete', 'our_products_publish', 'our_products_url'),
    'our_products_courses' => array('our_products_courses_add', 'our_products_courses_view', 'our_products_courses_edit', 'our_products_courses_delete', 'our_products_courses_active', 'our_products_courses_url'),
    'modules_trainings' => array('modules_trainings_add', 'modules_trainings_view', 'modules_trainings_edit', 'modules_trainings_delete', 'modules_trainings_active'),
    'modules_trainings_questions' => array('modules_trainings_questions_view', 'modules_trainings_questions_edit', 'modules_trainings_questions_delete', 'modules_trainings_questions_active'),
    'modules' => array('modules_add', 'modules_edit', 'modules_delete', 'modules_active', 'modules_view'),
    'modules_projects' => array('modules_projects_add', 'modules_projects_edit', 'modules_projects_delete', 'modules_projects_active', 'modules_projects_view'),
    'modules_users_projects' => array('modules_users_projects_add', 'modules_users_projects_edit', 'modules_users_projects_delete', 'modules_users_projects_active', 'modules_users_projects_view'),
    'modules_helper_courses' => array('modules_helper_courses_add', 'modules_helper_courses_edit', 'modules_helper_courses_delete', 'modules_helper_courses_active', 'modules_helper_courses_view'),
    'successstories' => array('successstories_add', 'successstories_edit', 'successstories_delete', 'successstories_publish', 'successstories_view'),
    'articles' => array('articles_add', 'articles_edit', 'articles_delete', 'articles_publish', 'articles_view'),
    'initiative_sections' => array('initiative_sections_add', 'initiative_sections_edit', 'initiative_sections_delete', 'initiative_sections_publish', 'initiative_sections_view'),
    'initiative_videos' => array('initiative_videos_add', 'initiative_videos_edit', 'initiative_videos_delete', 'initiative_videos_publish', 'initiative_videos_view'),
    'initiative_articles' => array('initiative_articles_add', 'initiative_articles_edit', 'initiative_articles_delete', 'initiative_articles_publish', 'initiative_articles_view'),
    'users_cvs' => array('users_cvs_view', 'users_cvs_download'),
    'demo_medical_logs' => array('demo_medical_logs_add', 'demo_medical_logs_edit', 'demo_medical_logs_delete', 'demo_medical_logs_view'),
    'categories' => array('categories_add', 'categories_edit', 'categories_delete', 'categories_active', 'categories_view'),
    'author' => array('author_add', 'author_edit', 'author_delete', 'author_publish', 'author_view'),
    'settings' => array('system', 'app_settings_edit', 'seo_sitemap_edit', 'subscription_prices_edit'),
    'our_partner' => array('our_partner_add', 'our_partner_view', 'our_partner_edit', 'our_partner_delete', 'our_partner_publish'),
    'our_partner_flags' => array('our_partner_flags_add', 'our_partner_flags_view', 'our_partner_flags_edit', 'our_partner_flags_delete', 'our_partner_flags_publish'),
    'request_courses' => array('request_courses_view'),
    'books_requests' => array('books_requests_view'),
    'company_request' => array('company_request_view','company_request_add', 'company_request_edit', 'company_request_delete'),
    'session_courses_views' => array('session_courses_views_add', 'session_courses_views_edit', 'session_courses_views_delete', 'session_courses_views_publish', 'session_courses_views_view'),
    'session_webinars_views' => array('session_webinars_views_add', 'session_webinars_views_edit', 'session_webinars_views_delete', 'session_webinars_views_publish', 'session_webinars_views_view'),
    'session_successtories_views' => array('session_successtories_views_add', 'session_successtories_views_edit', 'session_successtories_views_delete', 'session_successtories_views_publish', 'session_successtories_views_view'),
    'session_diplomas_views' => array('session_diplomas_views_view'),
    'blocked_users' => array('blocked_users_view'),
    'courses_views' => array('courses_views_add', 'courses_views_edit', 'courses_views_delete', 'courses_views_publish', 'courses_views_view'),
    'international_diplomas_views' => array('international_diplomas_views_add', 'international_diplomas_views_edit', 'international_diplomas_views_delete', 'international_diplomas_views_publish', 'international_diplomas_views_view'),
    'successtories_views' => array('successtories_views_add', 'successtories_views_edit', 'successtories_views_delete', 'successtories_views_publish', 'successtories_views_view'),
    'webinars_views' => array('webinars_views_add', 'webinars_views_edit', 'webinars_views_delete', 'webinars_views_publish', 'webinars_views_view'),
    'payment_transaction' => array('payment_transaction_add', 'payment_transaction_view', 'payment_transaction_edit', 'payment_transaction_delete', 'payment_transaction_publish'),
    'support_transaction' => array('support_transaction_add', 'support_transaction_edit', 'support_transaction_delete', 'support_transaction_publish', 'support_transaction_view'),
    'diplomas_charge_transaction' => array('diplomas_charge_transaction_add', 'diplomas_charge_transaction_view', 'diplomas_charge_transaction_edit', 'diplomas_charge_transaction_delete', 'diplomas_charge_transaction_publish', 'diplomas_charge_transaction_copy','diplomas_charge_transaction_add_courses'),
    'international_diplomas_charge_transaction' => array('international_diplomas_charge_transaction_add', 'international_diplomas_charge_transaction_view', 'international_diplomas_charge_transaction_edit', 'international_diplomas_charge_transaction_delete', 'international_diplomas_charge_transaction_publish', 'international_diplomas_charge_transaction_copy'),
    'diplomas_companies_charge_transaction' => array('diplomas_companies_charge_transaction_add', 'diplomas_companies_charge_transaction_view', 'diplomas_companies_charge_transaction_edit', 'diplomas_companies_charge_transaction_delete', 'diplomas_companies_charge_transaction_copy','diplomas_companies_charge_transaction_add_courses'),
    'diplomas_charge_transaction_suspend_log' => array('diplomas_charge_transaction_suspend_log_add', 'diplomas_charge_transaction_suspend_log_view', 'diplomas_charge_transaction_suspend_log_edit', 'diplomas_charge_transaction_suspend_log_delete', 'diplomas_charge_transaction_suspend_log_publish'),
    'international_diplomas_charge_transaction_suspend_log' => array('international_diplomas_charge_transaction_suspend_log_add', 'international_diplomas_charge_transaction_suspend_log_view', 'international_diplomas_charge_transaction_suspend_log_edit', 'international_diplomas_charge_transaction_suspend_log_delete', 'international_diplomas_charge_transaction_suspend_log_publish'),
    'medical_charge_transaction_suspend_log' => array('medical_charge_transaction_suspend_log_add', 'medical_charge_transaction_suspend_log_view', 'medical_charge_transaction_suspend_log_edit', 'medical_charge_transaction_suspend_log_delete', 'medical_charge_transaction_suspend_log_publish'),
    'mba_charge_transaction' => array('mba_charge_transaction_add', 'mba_charge_transaction_edit', 'mba_charge_transaction_delete', 'mba_charge_transaction_publish', 'mba_charge_transaction_view', 'mba_charge_transaction_copy'),
    'charge_transaction' => array('charge_transaction_add', 'charge_transaction_edit', 'charge_transaction_delete', 'charge_transaction_publish', 'charge_transaction_view', 'charge_transaction_copy'),
    'apple_users_charge_transactions' => array('apple_users_charge_transactions_add', 'apple_users_charge_transactions_edit', 'apple_users_charge_transactions_delete', 'apple_users_charge_transactions_view'),
    'contactus' => array('contactus_view'),
    'survey' => array('survey_view'),
    'feedback' => array('feedback_view','feedback_edit'),
    'rating' => array('rating_view'),
    'abuse' => array('abuse_view'),
    'modules_users_summary' => array('modules_users_summary_view','modules_users_summary_edit'),
    'courses_QandA' => array('courses_QandA_view','courses_QandA_edit'),
    'mlm_requests' => array('mlm_requests_view','mlm_requests_send'),
    //'survey2' => array('survey2_view'),

    'survey_clients' => array('survey_clients_view'),
    
    'medical_charge_transactions' => array('medical_charge_transactions_add', 'medical_charge_transactions_edit', 'medical_charge_transactions_delete', 'medical_charge_transactions_active', 'medical_charge_transactions_view', 'medical_charge_transactions_copy'),
    'medical_categories_charge_transactions' => array('medical_categories_charge_transactions_add', 'medical_categories_charge_transactions_edit', 'medical_categories_charge_transactions_delete', 'medical_categories_charge_transactions_active', 'medical_categories_charge_transactions_view', 'medical_categories_charge_transactions_copy'),
    'lite_version_charge_transaction' => array('lite_version_charge_transaction_add', 'lite_version_charge_transaction_edit', 'lite_version_charge_transaction_delete', 'lite_version_charge_transaction_active', 'lite_version_charge_transaction_view'),

    'diplomas_courses_user_plan' => array('diplomas_courses_user_plan_add', 'diplomas_courses_user_plan_edit', 'diplomas_courses_user_plan_delete', 'diplomas_courses_user_plan_delete_all', 'diplomas_courses_user_plan_active', 'diplomas_courses_user_plan_view',    'diplomas_courses_user_plan_delete_selected',
    ),
    'international_diplomas_courses_user_plan' => array('international_diplomas_courses_user_plan_add', 'international_diplomas_courses_user_plan_edit', 'international_diplomas_courses_user_plan_delete', 'international_diplomas_courses_user_plan_active', 'international_diplomas_courses_user_plan_view'),
    'mba_courses_user_plan' => array('mba_courses_user_plan_add', 'mba_courses_user_plan_edit', 'mba_courses_user_plan_delete', 'mba_courses_user_plan_active', 'mba_courses_user_plan_view'),

    'companies_charge_transaction' => array('companies_charge_transaction_delete', 'companies_charge_transaction_view'),
    'lite_version_companies_charge_transaction' => array('lite_version_companies_charge_transaction_delete', 'lite_version_companies_charge_transaction_view'),
    'mba_companies_charge_transaction' => array('mba_companies_charge_transaction_delete', 'mba_companies_charge_transaction_view'),


    //'survey2_clients' => array('survey2_clients_view'),
);
